before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  -
    env:
      - CGO_ENABLED=0

    binary: vultr-cli

    asmflags:
      - -D mysymbol
      - all=-trimpath={{.Env.GOPATH}}

    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
      - ./dontoptimizeme=-N

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - 386

archives:
  -
    replacements:
      darwin: macOs
      linux: linux
      windows: windows
      386: 32-bit
      amd64: 64-bit

    format: tar.gz

    files:
      - none*

    format_overrides:
      - goos: windows
        format: zip


checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .ProjectName }}_v{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    name: vultr-cli

    github:
      owner: vultr
      name: homebrew-vultr-cli


    url_template: "https://github.com/vultr/homebrew-vultr-cli/releases/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: goreleaserbot
      email: opensource@vultr.com

    homepage: "https://github.com/vultr/vultr-cli"

    description: "Official command-line tool for Vultr services"

    dependencies:
      - go
    test: |
      output = shell_output("#{bin}/vultr-cli version 2>&1", 1)
      assert_match "Please export your VULTR API key as an environment variable, eg:\nexport VULTR_API_KEY='<api_key_from_vultr_account>'\n", output

    install: |
      ENV["GOPATH"] = buildpath
      ENV["GO111MODULE"] = "on"
      dir = buildpath/"src/github.com/vultr/vultr-cli"
      dir.install buildpath.children

      cd dir do
        system "go", "build", "-o", bin/"vultr-cli", "-ldflags", "-X main.Version=v#{version}"
        prefix.install_metafiles
      end

release:
  github:
    owner: vultr
    name: vultr-cli